# Make sure that
#   * the revs specified here match requirements-dev.txt
#   * the additional_dependencies here match requirements.txt
repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args:
        - --diff
        - --check
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        language: python
-   repo: https://github.com/PyCQA/pylint
    rev: v2.9.3
    hooks:
    -   id: pylint
        files: ^(main|bot/\w*).py$
        args:
          - --rcfile=setup.cfg
        additional_dependencies:
            - python-telegram-bot>=13.7,<14.0
            - emoji==1.2.0
            - Pillow==8.3.0
            - PyHyphen==3.0.1
            - pytz
            - git+https://gitlab.com/HirschHeissIch/ptbstats.git@v1.3.1
        language: python
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        files: ^(main|bot/\w*).py$
        language: python
        additional_dependencies:
            - python-telegram-bot>=13.7,<14.0
            - emoji==1.2.0
            - Pillow==8.2.0
            - PyHyphen==4.0.0
            - pytz
            - git+https://gitlab.com/HirschHeissIch/ptbstats.git@v1.3.1
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
    -   id: pyupgrade
        files: ^(main|bot/\w*).py$
        args:
          - --py36-plus